id: I6BC40504
legacy_id: P004518
ocr_import_info:
  bdrc_scan_id: W19873
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T09:48:45'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T15:43:53.884559+00:00'
last_modified: 2022-08-30 23:44:04.036258
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W19873
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW19873
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱལ་ཆེན་རྣམ་སྲས་ལ་བརྟེན་ནས་ནོར་དང་ཚེ་དཔལ་འགུགས་ཆོག
statistics:
  ocr_word_mean_confidence_index: 0.5588458050664681
  ocr_word_median_confidence_index: 0.5400000214576721
quality: null
bases:
  I1KG11735:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11735
      total_pages: 126
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG11735.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5588458050664681
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
