id: I6BC40504
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:49:35+00:00'
last_modified: '2022-06-08T01:38:55.857731+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19873
  title: རྒྱལ་ཆེན་རྣམ་སྲས་ལ་བརྟེན་ནས་ནོར་དང་ཚེ་དཔལ་འགུགས་ཆོག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5419':
      image_group_id: I1KG11735
      title: ''
      total_pages: 126
      order: 1
      base_file: 5419.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
