id: P004518
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:29:09.483176
source_metadata:
  id: bdr:W19873
  title: རྒྱལ་ཆེན་རྣམ་སྲས་ལ་བརྟེན་ནས་ནོར་དང་ཚེ་དཔལ་འགུགས་ཆོག
  author: ''
  volumes:
    3338d7dda369457f995fb677b795b05e:
      image_group_id: I1KG11735
      title: ''
      volume_number: 1
      total_pages: 126
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
