id: P004518
initial_creation_type: ocr
source_metadata:
  id: bdr:W19873
  title: རྒྱལ་ཆེན་རྣམ་སྲས་ལ་བརྟེན་ནས་ནོར་དང་ཚེ་དཔལ་འགུགས་ཆོག
  author: ''
  volumes:
    3338d7dda369457f995fb677b795b05e:
      image_group_id: I1KG11735
      title: ''
      volume_number: 1
      total_pages: 126
